
import React, { useState, useEffect } from 'react';
import { User, UserProgress, Language } from '../types';
import { generateGuardianReport } from '../services/geminiService';
import { translations } from '../translations';

interface Props {
  user: User;
  progress: UserProgress;
  language: Language;
  onBack: () => void;
  onSent: () => void;
}

const GuardianReportView: React.FC<Props> = ({ user, progress, language, onBack, onSent }) => {
  const [report, setReport] = useState<string>('');
  const [loading, setLoading] = useState(true);
  const [sending, setSending] = useState(false);

  const t = (key: string) => translations[language][key] || translations['English'][key] || key;

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const text = await generateGuardianReport(user, progress, language);
        setReport(text);
      } catch (err) {
        setReport("Failed to generate progress report. Please check your connection.");
      } finally {
        setLoading(false);
      }
    };
    fetchReport();
  }, [user, progress, language]);

  const handleSend = async () => {
    setSending(true);
    // Simulate API delay for sending email/SMS
    await new Promise(r => setTimeout(r, 2000));
    setSending(false);
    onSent();
    alert(`Progress report successfully sent to ${user.guardian?.email || user.guardian?.phone}!`);
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] space-y-4">
        <div className="w-12 h-12 border-4 border-dare-purple border-t-transparent rounded-full animate-spin"></div>
        <p className="font-black text-dare-purple uppercase tracking-widest animate-pulse">Drafting Progress Report...</p>
      </div>
    );
  }

  return (
    <div className="max-w-3xl mx-auto py-12 px-4 animate-fadeIn">
      <button onClick={onBack} className="mb-8 text-gray-400 font-bold hover:text-dare-teal transition-all flex items-center gap-2">
        ← Back to Profile
      </button>

      <div className="bg-white dark:bg-slate-900 rounded-[3rem] shadow-2xl overflow-hidden border border-gray-100 dark:border-slate-800">
        <div className="bg-dare-purple p-10 text-white flex justify-between items-center">
          <div>
            <h2 className="text-3xl font-black mb-1">Official Progress Report</h2>
            <p className="opacity-80 font-bold">Generated by darewast AI for {user.name}</p>
          </div>
          <div className="text-4xl">📄</div>
        </div>

        <div className="p-10">
          <div className="prose dark:prose-invert max-w-none text-gray-700 dark:text-gray-300 leading-relaxed bg-slate-50 dark:bg-slate-800/50 p-8 rounded-3xl border border-dashed border-gray-200 dark:border-slate-700 mb-10">
            {report.split('\n').map((line, i) => (
              <p key={i} className="mb-4">{line}</p>
            ))}
          </div>

          <div className="flex flex-col sm:flex-row gap-4">
            <button 
              onClick={handleSend}
              disabled={sending}
              className="flex-1 py-5 bg-dare-purple text-white rounded-2xl font-black text-xl shadow-xl hover:scale-[1.02] transition-all flex items-center justify-center gap-3 disabled:opacity-50"
            >
              {sending ? <div className="w-6 h-6 border-2 border-white border-t-transparent rounded-full animate-spin"></div> : `✉️ Send to ${user.guardian?.name || 'Guardian'}`}
            </button>
            <button 
              onClick={onBack}
              className="px-10 py-5 bg-gray-100 dark:bg-slate-800 text-gray-500 rounded-2xl font-black hover:bg-gray-200 transition-all"
            >
              Cancel
            </button>
          </div>
          
          <p className="mt-6 text-center text-[10px] font-black text-gray-400 uppercase tracking-widest">
            This report will be delivered via {user.guardian?.email ? 'Email' : 'SMS'}
          </p>
        </div>
      </div>
    </div>
  );
};

export default GuardianReportView;
